# -*- coding: utf-8 -*-
"""globalaihubpythoncourse_mustafasinantemizkaya_hw2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kpttK5tMwXRZgasI1ZenApjBHopwvjD6
"""

CV1={} #First CV is created here
CV1['Name']='Sait Faik'
CV1['Surname']='Abasıyanık'
CV1['Job']='Writer'

CV2={}  #Second CV is created here
CV2['Name']= 'Albert'
CV2['Surname']='Einstein'
CV2['Job']='Scientist'

CV3={}  #Third CV is created here
CV3['Name']='Winston'
CV3['Surname']='Churchill'
CV3['Job']='Politician'

CV4={}  #Fourth CV is created here
CV4['Name']='Jack'
CV4['Surname']='Daniels'
CV4['Job']='Whisky (:'

CV5={}  #Fifth CV is created here
CV5['Name']='Benazir'
CV5['Surname']='Butto'
CV5['Job']='Leader'

#I combined and printed all CV's in one dict type data
for key,value in CV1.items():
    CV_all[key] = [value, CV5[key], CV2[key], CV3[key], CV4[key]]
print(CV_all)