# -*- coding: utf-8 -*-
"""GlobalAIHubPythonCourse_MustafaSinanTemizkaya_HW1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16z3WssOaaWWDGY2oHiofudtThlxHAJE6
"""

odd_list=[1,3, 5, 7, 9 ] #Odds list

even_list=[0,2,4,6,8] #Evens list

merged_list=odd_list+even_list #Here I merged two lists. I didn't sort it because there was no point about it.

print(merged_list) #I wanted to show the merged list

multiplied_list=[variable*2 for variable in merged_list] #I multiplied each element in the list by 2.

print(multiplied_list)  #I wanted to show the multiplied list

for i in multiplied_list: #Here I stated the data types of the elements in the final list by using a loop.
  print(type(i))